name: action
on: [push, pull_request]
jobs:
  linter_name:
    name: runner, formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rickstaa/action-black@v1
        with:
          black_args: "--check --verbose"
      - uses: py-actions/flake8@v2
        with:
          args: "."
      - uses: isort/isort-action@v1   
      - name: Check for modified files
        id: git-check
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: 
          git commit -am "Auto changes"
          git push
          

   
