repos:
  - repo: local
    hooks:
      - id: flake8
        name: Linter
        entry: flake8 
        lanquage: system
        types: [python]
      - id: black
        name: Black formatter 
        entry: black --check 
        language: system
        types: [python]
      - id: isort 
        name: Sort imports
        entry: isort --check 
        language: system
        types: [python]
