name: black, flake, isert
on: [push, pull_request]
jobs:
  format:
    name: formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rickstaa/action-black@v1
        with:
          args: ". --check"
      - uses: actions/checkout@v2
      - uses: rickstaa/action-flake8@v1
        with:
          args: "."
      - uses: actions/checkout@v2
      - uses: rickstaa/action-isert@v1
        with:
          args: "."    
          
          



    
